apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  generation: 1
  name: luconfig.garena.com
spec:
  conversion:
    strategy: None
  group: garena.com
  names:
    kind: LuConfig
    listKind: LuConfigList
    plural: luconfig
    shortNames:
    - luc
    singular: luconfig
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
