apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: 
      insecure-skip-tls-verify: false
      server: 
    name: 
contexts:
  - context:
      cluster: 
      user:
    name:
current-context:
kind: Config
users:
  - name:
    user:
      token:
