{{- if .Values.webui.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-user-manager.fullname" . }}-webui
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kube-user-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: webui
spec:
  replicas: {{ .Values.webui.replicas }}
  selector:
    matchLabels:
      {{- include "kube-user-manager.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: webui
  template:
    metadata:
      labels:
        {{- include "kube-user-manager.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: webui
    spec:
      serviceAccountName: {{ include "kube-user-manager.serviceAccountName" . }}
      containers:
        - name: webui
          image: "{{ .Values.webui.image.repository }}:{{ .Values.webui.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.webui.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.webui.service.targetPort }}
              protocol: TCP
          env:
            - name: SECRET_KEY
              value: {{ .Values.webui.auth.secretKey | quote }}
            - name: ADMIN_USERNAME
              value: {{ .Values.webui.auth.adminUsername | quote }}
            - name: ADMIN_PASSWORD
              value: {{ .Values.webui.auth.adminPassword | quote }}
            - name: CLUSTER_NAME
              value: {{ .Values.operator.cluster.name | quote }}
            - name: KUBE_API_URL
              value: {{ .Values.operator.cluster.apiUrl | quote }}
          livenessProbe:
            httpGet:
              path: /api/me
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/me
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            {{- toYaml .Values.webui.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

