apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: luconfig.osip.cc
spec:
  scope: Namespaced
  group: osip.cc
  names:
    kind: LuConfig
    plural: luconfig
    singular: luconfig
    shortNames:
      - luc
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
